### ISSUE TITLE
Error with get_network_score

### ISSUE THREAD

**Issue by mvhunter1** [morris-lab/CellOracle#106]
Hi, thanks for this great tool!

I'm going through the CellOracle workflow trying to apply the tool to my existing zebrafish scRNA-seq data. Everything has worked great (thank you for the very clear documentation) until the network preprocessing step. I got the following error from running ```links.get_network_score()```

Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-82-a9de07172873>", line 2, in <module>
    links.get_network_score()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/celloracle/network_analysis/links_object.py", line 181, in get_network_score
    df = _get_network_score(filtered_linklist_df=val)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/celloracle/network_analysis/links_object.py", line 518, in _get_network_score
    g = Graph.DataFrame(filtered_linklist_df[["source", "target"]],
AttributeError: type object 'Graph' has no attribute 'DataFrame'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2057, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/ultratb.py", line 818, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/ultratb.py", line 736, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stack_data/core.py", line 734, in lines
    pieces = self.included_pieces
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stack_data/core.py", line 677, in included_pieces
    scope_pieces = self.scope_pieces
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stack_data/core.py", line 614, in scope_pieces
    scope_start, scope_end = self.source.line_range(self.scope)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stack_data/core.py", line 178, in line_range
    return line_range(self.asttext(), node)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/executing/executing.py", line 428, in asttext
    self._asttext = ASTText(self.text, tree=self.tree, filename=self.filename)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/asttokens/asttokens.py", line 307, in __init__
    super(ASTText, self).__init__(source_text, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/asttokens/asttokens.py", line 44, in __init__
    source_text = six.ensure_text(source_text)
AttributeError: module 'six' has no attribute 'ensure_text'

I'm not super experienced with Python so it's very possible this could relate to something I did wrong, but just wanted to get your take. Thanks in advance!

**Comment by KenjiKamimoto-wustl122** [comment]
@mvhunter1 

Thank you very much for using celloracle and giving us your feedback!
It seems that the error is due to the incompatibility of python-igraph, one of the celloracle dependent packages.

I'd like to know some package version in your environment.
Can you please run the following code on your PC and tell me the outcome?
```
import celloracle as co
co.check_python_requirements()
```
I think I can easily fix the error with that information.

**Comment by KenjiKamimoto-wustl122** [comment]
@mvhunter1 

Thank you for the information.
I could reproduce the error with python-igraph 0.8.2.
For a quick fix, can you please update python-igraph version?
On a terminal window, please install a newer version of python-igraph like this.
I confirmed version 0.9.9 is fine.
```pip install python-igraph==0.9.9```

Can you please try `get_network_score` function after updating it? 
Hopefully `get_network_score` function will work with the newer version of python-igraph.

**Comment by mvhunter1** [comment]
Thank you! I updated my igraph to the version you suggested. Unfortunately, the updated version of igraph caused another error when I try to load the required packages. 

```
import os
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scanpy as sc
import seaborn as sns

Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-8487a973f2f7>", line 7, in <module>
    import scanpy as sc
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scanpy/__init__.py", line 14, in <module>
    from . import tools as tl
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scanpy/tools/__init__.py", line 15, in <module>
    from ._leiden import leiden
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scanpy/tools/_leiden.py", line 15, in <module>
    from leidenalg.VertexPartition import MutableVertexPartition
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/leidenalg/__init__.py", line 35, in <module>
    from .functions import ALL_COMMS
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/leidenalg/functions.py", line 23, in <module>
    from .VertexPartition import *
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/leidenalg/VertexPartition.py", line 8, in <module>
    class MutableVertexPartition(_ig.VertexClustering):
AttributeError: module 'igraph' has no attribute 'VertexClustering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2057, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/ultratb.py", line 818, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/ultratb.py", line 736, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stack_data/core.py", line 734, in lines
    pieces = self.included_pieces
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stack_data/core.py", line 677, in included_pieces
    scope_pieces = self.scope_pieces
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stack_data/core.py", line 614, in scope_pieces
    scope_start, scope_end = self.source.line_range(self.scope)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stack_data/core.py", line 178, in line_range
    return line_range(self.asttext(), node)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/executing/executing.py", line 428, in asttext
    self._asttext = ASTText(self.text, tree=self.tree, filename=self.filename)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/asttokens/asttokens.py", line 307, in __init__
    super(ASTText, self).__init__(source_text, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/asttokens/asttokens.py", line 44, in __init__
    source_text = six.ensure_text(source_text)
AttributeError: module 'six' has no attribute 'ensure_text'
```
For what it's worth, I was able to run ```links.get_score()``` successfully after installing the required R packages, but I understand you are trying to remove the requirement to install R packages to be able to run this :)

**Comment by KenjiKamimoto-wustl122** [comment]
@mvhunter1 

It seems the issue is the same as this one https://github.com/scverse/scanpy/issues/961
Can you please try to uninstall `python-igraph` and `scanpy` once, then re-install them following their instruction?
I'm guessing an old file is remaining and causing some errors.

**Comment by szhorvat** [comment]
> pip install python-igraph==0.9.9

`python-igraph` has been renamed to simply `igraph`. In the 0.9 series, the latest version is 0.9.11. You should really use that, or ideally 0.10.4 if there is no special reason to stick with 0.9. Note that you'll need louvain 0.8 for compatibility with igraph 0.10.

**Comment by mvhunter1** [comment]
Thank you! I uninstalled and reinstalled scanpy and python-igraph and ```links.get_network_score()``` seems to be working now. FYI, I installed the latest version of igraph (0.10.4) and it seems to work fine with CellOracle so far.

**Comment by KenjiKamimoto-wustl122** [comment]
@szhorvat @mvhunter1
 
Thank you so much!! For the next celloracle release, we will change the celloracle requirement to specify igraph 0.10.
