### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by heroineray** [morris-lab/CellOracle#140]
Hi！
When installing CellOracle, I had some troubles and got the following issues.
(I followed the steps in the document.)

```
Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      '.' is not recognized as an internal or external command, operable program or batch file.
      '.' is not recognized as an internal or external command, operable program or batch file.
      # pysam: htslib configure options: None
      Traceback (most recent call last):
        File "C:\Users\ray\.conda\envs\celloracle_env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>  
          main()
        File "C:\Users\ray\.conda\envs\celloracle_env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main      
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\ray\.conda\envs\celloracle_env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\ray\AppData\Local\Temp\pip-build-env-0qxdoxpv\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\ray\AppData\Local\Temp\pip-build-env-0qxdoxpv\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\ray\AppData\Local\Temp\pip-build-env-0qxdoxpv\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup        
          super(_BuildMetaLegacyBackend,
        File "C:\Users\ray\AppData\Local\Temp\pip-build-env-0qxdoxpv\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup        
          exec(code, locals())
        File "<string>", line 383, in <module>
        File "<string>", line 79, in run_make_print_config
        File "C:\Users\ray\.conda\envs\celloracle_env\lib\subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\ray\.conda\envs\celloracle_env\lib\subprocess.py", line 493, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\ray\.conda\envs\celloracle_env\lib\subprocess.py", line 858, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\ray\.conda\envs\celloracle_env\lib\subprocess.py", line 1311, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2]  the System Cannot Find the File Specified.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

My computer is using Windows11.
Is there any guidance on what might be going on and how this could be fixed? Many thanks in advance.

**Comment by KenjiKamimoto-wustl122** [comment]
@heroineray 

CellOracle is not supported in Windows OS because some dependencies cannot be used in Windows.
Please see requirements for related information. https://morris-lab.github.io/CellOracle.documentation/installation/index.html#system-requirements
Sorry for the inconvenience.

**Comment by heroineray** [comment]
> @heroineray
> 
> CellOracle is not supported in Windows OS because some dependencies cannot be used in Windows. Please see requirements for related information. https://morris-lab.github.io/CellOracle.documentation/installation/index.html#system-requirements Sorry for the inconvenience.

I will try again on linux. Thank you for helping me.
