### ISSUE TITLE
error when loading oracle data

### ISSUE THREAD

**Issue by heroineray** [morris-lab/CellOracle#154]
Hello! Thank you for creating this wonderful package!
I found an error when using `oracle = co.data.load_tutorial_oracle_object()`. How can I solve this problem?
```
Found serious error when loading data. It might be because of discrepancy of dependent library. You are trying to load an object which was generated with a library of different version.
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/celloracle_env/lib/python3.8/site-packages/celloracle/trajectory/oracle_core.py", line 71, in load_oracle
    obj = load_hdf5(filename=file_path, obj_class=Oracle, ignore_attrs_if_err=["knn", "knn_smoothing_w", "pca"])
  File "/home/ray/anaconda3/envs/celloracle_env/lib/python3.8/site-packages/celloracle/utility/hdf5_processing.py", line 122, in load_hdf5
    _file = h5py.File(filename, "r")
  File "/home/ray/anaconda3/envs/celloracle_env/lib/python3.8/site-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/ray/anaconda3/envs/celloracle_env/lib/python3.8/site-packages/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 409600, sblock->base_addr = 0, stored_eof = 81507062)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ray/anaconda3/envs/celloracle_env/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-2eef2d105f79>", line 1, in <module>
    oracle = co.data.load_tutorial_oracle_object()
  File "/home/ray/anaconda3/envs/celloracle_env/lib/python3.8/site-packages/celloracle/data/load_data.py", line 118, in load_tutorial_oracle_object
    return load_hdf5.load_hdf5(path)
  File "/home/ray/anaconda3/envs/celloracle_env/lib/python3.8/site-packages/celloracle/utility/load_hdf5.py", line 35, in load_hdf5
    obj = load_oracle(file_path=file_path)
  File "/home/ray/anaconda3/envs/celloracle_env/lib/python3.8/site-packages/celloracle/trajectory/oracle_core.py", line 75, in load_oracle
    obj = load_hdf5(filename=file_path, obj_class=Oracle, ignore_attrs_if_err=["knn", "knn_smoothing_w", "pca"])
  File "/home/ray/anaconda3/envs/celloracle_env/lib/python3.8/site-packages/celloracle/utility/hdf5_processing.py", line 122, in load_hdf5
    _file = h5py.File(filename, "r")
  File "/home/ray/anaconda3/envs/celloracle_env/lib/python3.8/site-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/ray/anaconda3/envs/celloracle_env/lib/python3.8/site-packages/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 409600, sblock->base_addr = 0, stored_eof = 81507062
```
Session information:
```
Package                   Version
------------------------- --------
anndata                   0.9.1
anyio                     3.7.1
appdirs                   1.4.4
argon2-cffi               21.3.0
argon2-cffi-bindings      21.2.0
arrow                     1.2.3
asttokens                 2.2.1
attrs                     23.1.0
backcall                  0.2.0
beautifulsoup4            4.12.2
biofluff                  3.0.4
biopython                 1.81
biothings-client          0.2.6
bleach                    6.0.0
boltons                   23.0.0
Brotli                    1.0.9
cachetools                5.3.1
cattrs                    23.1.2
celloracle                0.14.0
certifi                   2023.5.7
cffi                      1.15.1
charset-normalizer        3.2.0
click                     8.1.4
colorama                  0.4.6
comm                      0.1.3
conda                     23.5.0
conda-package-handling    2.0.2
conda_package_streaming   0.8.0
configparser              5.3.0
contourpy                 1.1.0
cryptography              39.0.0
cycler                    0.11.0
Cython                    0.29.36
debugpy                   1.6.7
decorator                 5.1.1
defusedxml                0.7.1
diskcache                 5.6.1
dnspython                 2.3.0
docopt                    0.6.2
et-xmlfile                1.1.0
exceptiongroup            1.1.2
executing                 1.2.0
fastjsonschema            2.17.1
feather-format            0.4.1
filelock                  3.12.2
fonttools                 4.40.0
fqdn                      1.5.1
frozendict                2.3.8
genomepy                  0.16.1
gimmemotifs               0.17.0
goatools                  1.3.1
h5py                      3.9.0
HTSeq                     2.0.3
idna                      3.4
igraph                    0.10.5
importlib-metadata        6.8.0
importlib-resources       6.0.0
ipykernel                 6.24.0
ipython                   8.12.2
ipython-genutils          0.2.0
ipywidgets                8.0.7
isoduration               20.11.0
iteround                  1.0.3
itsdangerous              2.1.2
jedi                      0.18.2
Jinja2                    3.1.2
joblib                    1.3.0
jsonpatch                 1.32
jsonpointer               2.0
jsonschema                4.18.0
jsonschema-specifications 2023.6.1
jupyter                   1.0.0
jupyter_client            8.3.0
jupyter-console           6.6.3
jupyter_core              5.3.1
jupyter-events            0.6.3
jupyter_server            2.7.0
jupyter_server_terminals  0.4.4
jupyterlab-pygments       0.2.2
jupyterlab-widgets        3.0.8
kiwisolver                1.4.4
libmambapy                0.24.0
llvmlite                  0.40.1
logomaker                 0.8
loguru                    0.7.0
loompy                    3.0.7
louvain                   0.8.0
lxml                      4.9.2
mamba                     0.24.0
MarkupSafe                2.1.3
matplotlib                3.6.3
matplotlib-inline         0.1.6
mistune                   3.0.1
munkres                   1.1.4
mygene                    3.2.2
mysql-connector-python    8.0.32
natsort                   8.4.0
nbclassic                 1.0.0
nbclient                  0.8.0
nbconvert                 7.6.0
nbformat                  5.9.1
nest-asyncio              1.5.6
networkx                  3.1
norns                     0.1.6
nose                      1.3.7
notebook                  6.5.4
notebook_shim             0.2.3
numba                     0.57.1
numpy                     1.22.3
numpy-groupies            0.9.22
openpyxl                  3.1.2
overrides                 7.3.1
packaging                 23.1
palettable                3.3.3
pandas                    1.4.2
pandocfilters             1.5.0
parso                     0.8.3
patsy                     0.5.3
pexpect                   4.8.0
pickleshare               0.7.5
Pillow                    9.2.0
pip                       23.1.2
pkgutil_resolve_name      1.3.10
platformdirs              3.8.1
plotly                    5.15.0
pluggy                    1.2.0
ply                       3.11
pooch                     1.7.0
prometheus-client         0.17.1
prompt-toolkit            3.0.39
protobuf                  3.20.3
psutil                    5.9.5
ptyprocess                0.7.0
pure-eval                 0.2.2
pyarrow                   9.0.0
pybedtools                0.9.0
pyBigWig                  0.3.18
pycosat                   0.6.4
pycparser                 2.21
pydot                     1.4.2
pyfaidx                   0.7.2.1
Pygments                  2.15.1
PyLD                      2.0.3
pynndescent               0.5.10
pyOpenSSL                 23.2.0
pyparsing                 3.0.9
PyQt5                     5.15.7
PyQt5-sip                 12.11.0
pysam                     0.21.0
PySocks                   1.7.1
python-dateutil           2.8.2
python-json-logger        2.0.7
pytz                      2023.3
PyVCF3                    1.0.3
PyYAML                    6.0
pyzmq                     25.1.0
qnorm                     0.8.1
qtconsole                 5.4.3
QtPy                      2.3.1
referencing               0.29.1
requests                  2.31.0
requests-cache            1.1.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.8.10
ruamel.yaml               0.17.32
ruamel.yaml.clib          0.2.7
scanpy                    1.9.3
scikit-learn              1.3.0
scipy                     1.10.1
seaborn                   0.12.2
Send2Trash                1.8.2
session-info              1.0.0
setuptools                67.8.0
sip                       6.7.9
six                       1.16.0
sniffio                   1.3.0
soupsieve                 2.4.1
stack-data                0.6.2
statsmodels               0.14.0
stdlib-list               0.9.0
tenacity                  8.2.2
terminado                 0.17.1
texttable                 1.6.7
threadpoolctl             3.1.0
tinycss2                  1.2.1
toml                      0.10.2
tomli                     2.0.1
toolz                     0.12.0
tornado                   6.3.2
tqdm                      4.65.0
traitlets                 5.9.0
typing_extensions         4.7.1
ujson                     5.7.0
umap-learn                0.5.3
unicodedata2              15.0.0
uri-template              1.3.0
url-normalize             1.4.3
urllib3                   2.0.3
velocyto                  0.17.17
wcwidth                   0.2.6
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.6.1
wheel                     0.38.4
widgetsnbextension        4.0.8
xdg                       6.0.0
xgboost                   1.7.6
XlsxWriter                3.1.2
xxhash                    0.0.0
zipp                      3.16.0
zstandard                 0.19.0
```

**Comment by KenjiKamimoto-wustl122** [comment]
Hi @heroineray , thank you for the feedback!

I guess it may be caused by some incompatibility of celloracle dependent package. I'll look into it and try to solve it.
