### ISSUE TITLE
ImportError: cannot import name 'default_motifs' from 'gimmemotifs.motif'

### ISSUE THREAD

**Issue by acv21** [morris-lab/CellOracle#158]
Hello,

I am following [this](https://morris-lab.github.io/CellOracle.documentation/notebooks/02_motif_scan/02_atac_peaks_to_TFinfo_with_celloracle_20200801.html) tutorial to obtain a base GRN, with the code below. I get the following error message:

```
Traceback (most recent call last):
  File "15_4_CellOracle_base-GRN-preparation.py", line 12, in <module>
    import celloracle as co
  File "/dir/Packages/envs/celloracle_env/lib/python3.8/site-packages/celloracle/__init__.py", line 8, in <module>
    from . import utility, network, network_analysis, go_analysis, data, data_conversion, oracle_utility
  File "/dir/Packages/envs/celloracle_env/lib/python3.8/site-packages/celloracle/utility/__init__.py", line 18, in <module>
    from .load_hdf5 import load_hdf5
  File "/dir/Packages/envs/celloracle_env/lib/python3.8/site-packages/celloracle/utility/load_hdf5.py", line 8, in <module>
    from ..motif_analysis.tfinfo_core import load_TFinfo
  File "/dir/Packages/envs/celloracle_env/lib/python3.8/site-packages/celloracle/motif_analysis/__init__.py", line 13, in <module>
    from .tfinfo_core import (load_TFinfo, load_TFinfo_from_parquets,
  File "/dir/Packages/envs/celloracle_env/lib/python3.8/site-packages/celloracle/motif_analysis/tfinfo_core.py", line 38, in <module>
    from gimmemotifs.motif import default_motifs
ImportError: cannot import name 'default_motifs' from 'gimmemotifs.motif' (/dir/Packages/envs/celloracle_env/lib/python3.8/site-packages/gimmemotifs/motif/__init__.py)
```

I am not sure why it's not loading the default motifs from gimmemotifs. I have both gimmemotifs and celloracle installed in the same conda environment.

Here's the code:

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os, sys, shutil, importlib, glob
from tqdm.notebook import tqdm
from genomepy import Genome

import celloracle as co
from celloracle import motif_analysis as ma
from celloracle.utility import save_as_pickled_object
co.__version__

ref_genome = "hg38"

genome_installation = ma.is_genome_installed(ref_genome=ref_genome, genomes_dir="/dir/genomes")
print(ref_genome, "installation: ", genome_installation)

peaks = pd.read_csv("./objects/15_CellOracle_input-links.csv")
peaks.head()

peaks = ma.check_peak_format(peaks, ref_genome, genomes_dir="/dir/genomes")

# Instantiate TFinfo object
tfi = ma.TFinfo(peak_data_frame=peaks,
                ref_genome=ref_genome, genomes_dir="/dir/genomes")

# Scan motifs. !!CAUTION!! This step may take several hours if you have many peaks!
tfi.scan(fpr=0.02,
         motifs=None,  # If you enter None, default motifs will be loaded.
         verbose=True)

# Save tfinfo object
tfi.to_hdf5(file_path="test1.celloracle.tfinfo")

# Check motif scan results
tfi.scanned_df.head()

# ## Filter motifs

# Reset filtering
tfi.reset_filtering()

# Do filtering
tfi.filter_motifs_by_score(threshold=10)

# Format post-filtering results.
tfi.make_TFinfo_dataframe_and_dictionary(verbose=True)

# ## Final base GRN

df = tfi.to_dataframe()
df.head()


# ## Save data

# Save result as a dataframe
df = tfi.to_dataframe()
df.to_parquet("./objects/15_CellOracle_base-GRN.parquet")
df.to_csv("./objects/15_CellOracle_base-GRN.csv")
```

Thank you for your time!

**Comment by KenjiKamimoto-wustl122** [comment]
@990618 @acv21 

Sorry for the slow response.
Unfortunately I could not reproduce the error on my side.
I guess there is something wrong in the gimmemotifs installation.
Can you please try the below to check your gimmemotifs installation status?

```from gimmemotifs.motif import default_motifs```

If you can get the error, I recommend uninstall gimmemotifs and reinstall it.

**Comment by PedroMBarcelos** [comment]
Hey there, just run into this error and I downgraded the gimmemotif version from 0.18.0 to 0.14.4 and it worked.
Not sure what is causing this in the most updated version yet but this should be a quick fix.
