### ISSUE TITLE
Failed to load celloracle

### ISSUE THREAD

**Issue by YuchenXiangEMBL** [morris-lab/CellOracle#171]
I have tried to install celloracle 
`conda create -n celloracle_env python=3.8
conda activate celloracle_env`
`conda install -c bioconda pybedtools`
The installation was successful, however, when I try to import it, 
`import celloracle as co`
it reports error
`>>> import celloracle as co
//miniconda3/envs/celloracle_pybedtools/lib/python3.8/site-packages/loompy/bus_file.py:68: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def twobit_to_dna(twobit: int, size: int) -> str:
//miniconda3/envs/celloracle_pybedtools/lib/python3.8/site-packages/loompy/bus_file.py:85: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def dna_to_twobit(dna: str) -> int:
//miniconda3/envs/celloracle_pybedtools/lib/python3.8/site-packages/loompy/bus_file.py:102: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def twobit_1hamming(twobit: int, size: int) -> List[int]:
which: no R in (//miniconda3/envs/celloracle_pybedtools/bin://miniforge3/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin://.local/bin://bin)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/celloracle_pybedtools/lib/python3.8/site-packages/celloracle/__init__.py", line 8, in <module>
    from . import utility, network, network_analysis, go_analysis, data, data_conversion, oracle_utility
  File "/miniconda3/envs/celloracle_pybedtools/lib/python3.8/site-packages/celloracle/utility/__init__.py", line 18, in <module>
    from .load_hdf5 import load_hdf5
  File "/miniconda3/envs/celloracle_pybedtools/lib/python3.8/site-packages/celloracle/utility/load_hdf5.py", line 8, in <module>
    from ..motif_analysis.tfinfo_core import load_TFinfo
  File "/miniconda3/envs/celloracle_pybedtools/lib/python3.8/site-packages/celloracle/motif_analysis/__init__.py", line 11, in <module>
    from .motif_analysis_utility import is_genome_installed
  File "/miniconda3/envs/celloracle_pybedtools/lib/python3.8/site-packages/celloracle/motif_analysis/motif_analysis_utility.py", line 25, in <module>
    from gimmemotifs.scanner import Scanner
  File "/miniconda3/envs/celloracle_pybedtools/lib/python3.8/site-packages/gimmemotifs/__init__.py", line 58, in <module>
    from . import background  # noqa: F401
  File "/miniconda3/envs/celloracle_pybedtools/lib/python3.8/site-packages/gimmemotifs/background.py", line 27, in <module>
    import pybedtools
  File "/miniconda3/envs/celloracle_pybedtools/lib/python3.8/site-packages/pybedtools/__init__.py", line 8, in <module>
    from .cbedtools import (
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by //miniconda3/envs/celloracle_pybedtools/lib/python3.8/site-packages/pybedtools/cbedtools.cpython-38-x86_64-linux-gnu.so)`
And I tried to import pybedtools first and then import celloracle
`>>> import pybedtools
>>> import celloracle as co`
I am not sure what's going on and why the pybedtools need to use the system GLIBCXX

**Comment by KenjiKamimoto-wustl122** [comment]
It seems your pybedtools installation is broken because of some random reasons.
Can you uninstall and reinstall pybedtools?
And please make sure you can import pybedtools without problem by running just `import pybedtools`.
And then, please try celloracle.

**Comment by PauBadiaM** [comment]
It seems like the new version `0.9.1` of `pybedtools` has issues with `gcc`. After downgrading to `0.9.0` it worked for me.
```
pip install pybedtools==0.9.0
```
