### ISSUE TITLE
Matplotlib on macosx - python as framework

### ISSUE THREAD

**Issue by macrinalobo** [morris-lab/CellOracle#21]
Hi,

After the conda installation following the steps documented, when importing cell oracle, I got the following error - 

>>> import celloracle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../CellOracle/celloracle/__init__.py", line 8, in <module>
    from . import utility, network, network_analysis, go_analysis, data, data_conversion
  File "../CellOracle/celloracle/utility/__init__.py", line 13, in <module>
    from .load_hdf5 import load_hdf5
  File "../CellOracle/celloracle/utility/load_hdf5.py", line 5, in <module>
    from ..network_analysis import load_links
  File "../CellOracle/celloracle/network_analysis/__init__.py", line 7, in <module>
    from . import gene_analysis
  File "../CellOracle/celloracle/network_analysis/gene_analysis.py", line 19, in <module>
    import matplotlib.pyplot as plt
  File "../miniconda3/envs/celloracle_env_new2/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2372, in <module>
    switch_backend(rcParams["backend"])
  File "../miniconda3/envs/celloracle_env_new2/lib/python3.6/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "../miniconda3/envs/celloracle_env_new2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "../miniconda3/envs/celloracle_env_new2/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py", line 14, in <module>
    from matplotlib.backends import _macosx
ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.

>>> matplotlib.__version__
'3.0.3'

I fixed this by adding

import matplotlib
if platform == "darwin":  # OS X
     matplotlib.use('TkAgg')

before 

import matplotlib.pyplot as plt

in all celloracle .py files that imported matplotlib.

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Macrina,

Thank you for sharing the error with us! The solution is useful too!

Thanks,
