### ISSUE TITLE
Mac OS install

### ISSUE THREAD

**Issue by concatenize** [morris-lab/CellOracle#3]
Hi, I just wanted to share my experience installing on Mac OS 10.14.6 (Mojave). For velocyto, I hit an error very similar to [this](https://github.com/velocyto-team/velocyto.R/issues/2). It was fixed by doing `conda install gcc llvm` before retrying `conda install velocyto`. With the celloracle install, I worked through some errors by doing `conda install cmake` and `conda install -c psi4 gcc-5`. Here are the details.

With the celloracle install, I first got this error:

```
ERROR: Command errored out with exit status 1:
     command: //anaconda/envs/celloracle_env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-xktd3clu/xgboost/setup.py'"'"'; __file__='"'"'/private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-xktd3clu/xgboost/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-xktd3clu/xgboost/pip-egg-info
         cwd: /private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-xktd3clu/xgboost/
    Complete output (27 lines):
    ++ pwd
    + oldpath=/private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-xktd3clu/xgboost
    + cd ./xgboost/
    + mkdir -p build
    + cd build
    + cmake ..
    ./xgboost/build-python.sh: line 21: cmake: command not found
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + cmake .. -DUSE_OPENMP=0
    ./xgboost/build-python.sh: line 27: cmake: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-xktd3clu/xgboost/setup.py", line 42, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-xktd3clu/xgboost/xgboost/libpath.py", line 50, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-xktd3clu/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-xktd3clu/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-xktd3clu/xgboost/xgboost/./lib/libxgboost.dylib
    //anaconda/envs/celloracle_env/xgboost/libxgboost.dylib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

This error remains after `conda install xgboost`, but after `conda install cmake`, it changes to the following. 

```
  ERROR: Command errored out with exit status 1:
     command: //anaconda/envs/celloracle_env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-t3ki2ri1/xgboost/setup.py'"'"'; __file__='"'"'/private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-t3ki2ri1/xgboost/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-t3ki2ri1/xgboost/pip-egg-info
         cwd: /private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-t3ki2ri1/xgboost/
    Complete output (61 lines):
    ++ pwd
    + oldpath=/private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-t3ki2ri1/xgboost
    + cd ./xgboost/
    + mkdir -p build
    + cd build
    + cmake ..
    -- The CXX compiler identification is GNU 4.8.5
    -- The C compiler identification is GNU 4.8.5
    -- Checking whether CXX compiler has -isysroot
    -- Checking whether CXX compiler has -isysroot - yes
    -- Checking whether CXX compiler supports OSX deployment target flag
    -- Checking whether CXX compiler supports OSX deployment target flag - yes
    -- Check for working CXX compiler: /anaconda/envs/celloracle_env/bin/c++
    -- Check for working CXX compiler: /anaconda/envs/celloracle_env/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Checking whether C compiler has -isysroot
    -- Checking whether C compiler has -isysroot - yes
    -- Checking whether C compiler supports OSX deployment target flag
    -- Checking whether C compiler supports OSX deployment target flag - yes
    -- Check for working C compiler: /anaconda/envs/celloracle_env/bin/cc
    -- Check for working C compiler: /anaconda/envs/celloracle_env/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- CMake version 3.14.0
    CMake Error at CMakeLists.txt:14 (message):
      GCC version must be at least 5.0!


    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-t3ki2ri1/xgboost/xgboost/build/CMakeFiles/CMakeOutput.log".
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + cmake .. -DUSE_OPENMP=0
    -- CMake version 3.14.0
    CMake Error at CMakeLists.txt:14 (message):
      GCC version must be at least 5.0!


    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-t3ki2ri1/xgboost/xgboost/build/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-t3ki2ri1/xgboost/setup.py", line 42, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-t3ki2ri1/xgboost/xgboost/libpath.py", line 50, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-t3ki2ri1/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-t3ki2ri1/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/8q/3gpm_n1j5rb5_8f1qrdc_1nh0000gn/T/pip-install-t3ki2ri1/xgboost/xgboost/./lib/libxgboost.dylib
    //anaconda/envs/celloracle_env/xgboost/libxgboost.dylib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I then upgraded gcc with `conda install -c psi4 gcc-5` and verified that `gcc --version` shows version 5.x. After that, the celloracle installation worked.

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Concatenize,

Thank you so much for sharing the problem and solutions! It helps us a lot!! 
I will add the link to this GitHub-issue page to celloracle documentation!.
