### ISSUE TITLE
error when run get_links

### ISSUE THREAD

**Issue by yzz207** [morris-lab/CellOracle#4]
Hi, 

I got "No model found. Do fit first." error when using get_links. What model it refers to? I am not sure if I missed a step or anything.

>>> links = oracle.get_links(cluster_name_for_GRN_unit="free_annotation", alpha=10,
...                          verbose_level=0, test_mode=True)
No model found. Do fit first.
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/conda/lib/python3.7/site-packages/celloracle/trajectory/oracle_core.py", line 649, in get_links
    verbose_level=verbose_level, test_mode=test_mode)
  File "/opt/conda/lib/python3.7/site-packages/celloracle/network_analysis/network_construction.py", line 68, in get_links
    alpha=alpha, bagging_number=bagging_number,  verbose_level=verbose_level, test_mode=test_mode)
  File "/opt/conda/lib/python3.7/site-packages/celloracle/network_analysis/network_construction.py", line 128, in _fit_GRN_for_network_analysis
    tn_.updateLinkList(verbose=False)
  File "/opt/conda/lib/python3.7/site-packages/celloracle/network/net_core.py", line 516, in updateLinkList
    linkList = pd.concat(linkList, axis=0)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 281, in concat
    sort=sort,
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 329, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

Thanks,
Yuping

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Yuping,

The error means that your GRN calculation failed and there is no network edge in your GRN inference results. I guess something wrong with your scRNA-seq data format or transcription factor information. I need to know two things to clarify the problems.

1) Can you please try the command below in your python notebook and tell me outputs?

# Check your gene names in your scRNA-seq data 
oracle.adata.var.index.values[:20]

2) Can you please try the commands below  in your python notebook and tell me outputs?

# Check your transcription factor information
list(oracle.TFdict.keys())[::200]

**Comment by yzz207** [comment]
Thank you very much. After checking the gene names as you suggested, I think I know the reason. The built-in TFinfo_df is for mouse, but I have human data. Do you have TF info for human?

**Comment by KenjiKamimoto-wustl122** [comment]
Currently we do not provide general TF info for human because there is no human scATAC-seq dataset for whole body now.  Thus you need to get scATAC-seq data of your cells and build TF-info yourself. You can do it by using out python notebook in tutorial-1 and tutorial-2.

Also, we are planning to update / add built-in TF-info in the future.
