### ISSUE TITLE
Errors when converting Seurat to anndata

### ISSUE THREAD

**Issue by laurabchopp** [morris-lab/CellOracle#62]
Hi there,

I have successfully converted a Seurat object into anndata in the past, but now every way I try it--it fails.

When using on API:

seuratToAnndata "/data/path/WTRNA.rds" "/data/path/MouseAnnData"

I get the following error 

saving AnnData as h5ad file ...
... storing 'orig.ident' as categorical
... storing 'genotype' as categorical
... storing 'orignal' as categorical
... storing 'exp' as categorical
... storing 'ID' as categorical
... storing 'cluster' as categorical
... storing 'assignedname' as categorical
... storing 'active_ident' as categorical
Traceback (most recent call last):
  File "/data/chopplb/conda/envs/celloracle_env/lib/python3.6/site-packages/anndata/_io/utils.py", line 209, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/data/chopplb/conda/envs/celloracle_env/lib/python3.6/site-packages/anndata/_io/h5ad.py", line 274, in write_series
    **dataset_kwargs,
  File "/data/chopplb/conda/envs/celloracle_env/lib/python3.6/site-packages/h5py/_hl/group.py", line 148, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/data/chopplb/conda/envs/celloracle_env/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 140, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 232, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 145, in h5py._proxy.dset_rw
  File "h5py/_conv.pyx", line 443, in h5py._conv.str2vlen
  File "h5py/_conv.pyx", line 94, in h5py._conv.generic_converter
  File "h5py/_conv.pyx", line 248, in h5py._conv.conv_str2vlen
TypeError: Can't implicitly convert non-string objects to strings

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/chopplb/conda/envs/celloracle_env/lib/python3.6/site-packages/anndata/_io/utils.py", line 209, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/data/chopplb/conda/envs/celloracle_env/lib/python3.6/site-packages/anndata/_io/h5ad.py", line 263, in write_dataframe
    write_series(group, col_name, series, dataset_kwargs=dataset_kwargs)
  File "/data/chopplb/conda/envs/celloracle_env/lib/python3.6/site-packages/anndata/_io/utils.py", line 216, in func_wrapper
    ) from e
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'seurat_clusters' of <class 'h5py._hl.group.Group'> from /.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/chopplb/conda/envs/celloracle_env/bin/seuratToAnndata", line 8, in <module>
    sys.exit(main())
  File "/data/chopplb/conda/envs/celloracle_env/lib/python3.6/site-packages/celloracle/data_conversion/process_seurat_object.py", line 134, in main
    adata.write(filename=output_file_name.replace(".h5ad", f"_{assay_name}.h5ad"))
  File "/data/chopplb/conda/envs/celloracle_env/lib/python3.6/site-packages/anndata/_core/anndata.py", line 1911, in write_h5ad
    as_dense=as_dense,
  File "/data/chopplb/conda/envs/celloracle_env/lib/python3.6/site-packages/anndata/_io/h5ad.py", line 111, in write_h5ad
    write_attribute(f, "obs", adata.obs, dataset_kwargs=dataset_kwargs)
  File "/data/chopplb/conda/envs/celloracle_env/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/data/chopplb/conda/envs/celloracle_env/lib/python3.6/site-packages/anndata/_io/h5ad.py", line 130, in write_attribute_h5ad
    _write_method(type(value))(f, key, value, *args, **kwargs)
  File "/data/chopplb/conda/envs/celloracle_env/lib/python3.6/site-packages/anndata/_io/utils.py", line 216, in func_wrapper
    ) from e
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'seurat_clusters' of <class 'h5py._hl.group.Group'> from /.

Above error raised while writing key 'obs' of <class 'h5py._hl.files.File'> from /.

When I tried using the cell oracle command

celloracle.data_conversion.seurat_object_to_anndata(file_path_seurat_object,

It doesn't give an error, and successfully makes temp files, but at the end there is no anndata object. I have also tried using Seurat's own conversion to anndata using, but when I try to run cell oracle, I get this error:

>>> oracle.import_anndata_as_raw_count(adata=adata,
...                                    cluster_column_name="seurat_clusters",
...                                    embedding_name="X_umap")
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/data/chopplb/conda/lib/python3.7/site-packages/celloracle/trajectory/oracle_core.py", line 382, in import_anndata_as_raw_count
    return_as="dict")
  File "/data/chopplb/conda/lib/python3.7/site-packages/celloracle/trajectory/oracle_utility.py", line 139, in _get_clustercolor_from_anndata
    pal = get_palette(adata, cluster_name)
  File "/data/chopplb/conda/lib/python3.7/site-packages/celloracle/trajectory/oracle_utility.py", line 128, in get_palette
    c = [i.upper() for i in adata.uns[f"{cname}_colors"]]
  File "/data/chopplb/conda/lib/python3.7/site-packages/anndata/compat/_overloaded_dict.py", line 100, in __getitem__
    return self.data[key]
KeyError: 'seurat_clusters_colors'

I'm really at a loss as to how to proceed, and any guidance would be much appreciated! Thanks!

**Comment by laurabchopp** [comment]
I tracked the error to Seurat metadata--removing all unnecessary metadata solved the issue. As to the KeyError: 'seurat_cluster_colors' issue, https://github.com/morris-lab/CellOracle/issues/46 solved it.
