### ISSUE TITLE
import celloracle ValueError: numpy.ndarray size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by elhaam** [morris-lab/CellOracle#82]
Hello! Thank you for this very useful package. 
I am facing the following error simply after following the installation guide. Would you please help me with this?

> Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
 import celloracle as co 
>
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ejafari/.conda/envs/celloracle_env/lib/python3.8/site-packages/celloracle/__init__.py", line 8, in <module>
    from . import utility, network, network_analysis, go_analysis, data, data_conversion, oracle_utility
  File "/home/ejafari/.conda/envs/celloracle_env/lib/python3.8/site-packages/celloracle/utility/__init__.py", line 18, in <module>
    from .load_hdf5 import load_hdf5
  File "/home/ejafari/.conda/envs/celloracle_env/lib/python3.8/site-packages/celloracle/utility/load_hdf5.py", line 5, in <module>
    from ..network_analysis import load_links
  File "/home/ejafari/.conda/envs/celloracle_env/lib/python3.8/site-packages/celloracle/network_analysis/__init__.py", line 9, in <module>
    from .network_construction import get_links
  File "/home/ejafari/.conda/envs/celloracle_env/lib/python3.8/site-packages/celloracle/network_analysis/network_construction.py", line 26, in <module>
    from ..network.net_core import Net
  File "/home/ejafari/.conda/envs/celloracle_env/lib/python3.8/site-packages/celloracle/network/__init__.py", line 7, in <module>
    from .net_util import load_net_from_patquets, getDF_TGxTF, getDF_peakxTF, load_net
  File "/home/ejafari/.conda/envs/celloracle_env/lib/python3.8/site-packages/celloracle/network/net_util.py", line 26, in <module>
    from velocyto.serialization import dump_hdf5, load_hdf5
  File "/home/ejafari/.conda/envs/celloracle_env/lib/python3.8/site-packages/velocyto/__init__.py", line 13, in <module>
    from .estimation import fit_slope, _fit1_slope, clusters_stats
  File "/home/ejafari/.conda/envs/celloracle_env/lib/python3.8/site-packages/velocyto/estimation.py", line 7, in <module>
    from .speedboosted import _colDeltaCor, _colDeltaCorLog10, _colDeltaCorSqrt
  File "velocyto/speedboosted.pyx", line 1, in init velocyto.speedboosted
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
`

I also tried the methods mentioned in the Celloracle tutorial as well as installing different versions of my NumPy package, but that did not fix the issue.
Thank you!

**Comment by elhaam** [comment]
Quick solution if anyone faces this issue in the future: 

I fixed the problem by creating a new environment and this time, I installed velocyto package by following commands, according to their GitHub:

> git clone https://github.com/velocyto-team/velocyto.py.git
> cd velocyto.py
> pip install -e .  # note the trailing dot

After that, I simply installed Celloracle and this fixed the previous error.

> pip install git+https://github.com/morris-lab/CellOracle.git

Hope this helps :)

**Comment by KenjiKamimoto-wustl122** [comment]
@elhaam 
I'm glad that the issue was solved. Thank you for sharing the solution!
